#--------------------------
# Working with CPack
#
# Copyright (c) by steppans 2022

name: Formatter_INC

on:
  push:
    branches:
      - main

jobs:
  my_test_linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: Check existance of cmake
      run : cmake --version
    
    - name: Make builds
      run : |
        mkdir cmake-build && cd cmake-build
        cmake ..
        make
    - name: First attempt to run solver_application
      run : | 
        cd cmake-build/solver_application
        ./solver 1 2 1
    - name: Second attempt to run solver_application
      run : | 
        cd cmake-build/solver_application
        ./solver 21 16 9
